import { Product, ProductCategory } from "@/types/product.types";
import { InventoryItem, StockStatus } from "@/types/inventory.types";
import { User, UserRole, UserStatus } from "@/types/user.types";

export const PRODUCTS: Product[] = [
  {
    id: 32,
    name: "Chocolate Chip Cookie",
    price: 2.49,
    image: "https://picsum.photos/300/300?random=12",
    category: ProductCategory.DESSERT,
  },
  {
    id: 4,
    name: "Americano",
    price: 3.49,
    image: "https://picsum.photos/300/300?random=4",
    category: ProductCategory.COFFEE,
  },
  {
    id: 21,
    name: "Chicken Wrap",
    price: 8.49,
    image: "https://picsum.photos/300/300?random=31",
    category: ProductCategory.FOOD,
  },
  {
    id: 37,
    name: "Strawberry Tart",
    price: 5.49,
    image: "https://picsum.photos/300/300?random=45",
    category: ProductCategory.DESSERT,
  },
  {
    id: 7,
    name: "Chai Latte",
    price: 4.59,
    image: "https://picsum.photos/300/300?random=9",
    category: ProductCategory.COFFEE,
  },
  {
    id: 25,
    name: "Soup of the Day",
    price: 5.99,
    image: "https://picsum.photos/300/300?random=35",
    category: ProductCategory.FOOD,
  },
  {
    id: 41,
    name: "Red Velvet Cake",
    price: 5.99,
    image: "https://picsum.photos/300/300?random=49",
    category: ProductCategory.DESSERT,
  },
  {
    id: 12,
    name: "Frappuccino",
    price: 5.29,
    image: "https://picsum.photos/300/300?random=24",
    category: ProductCategory.COFFEE,
  },
  {
    id: 18,
    name: "Avocado Toast",
    price: 6.99,
    image: "https://picsum.photos/300/300?random=28",
    category: ProductCategory.FOOD,
  },
  {
    id: 36,
    name: "Tiramisu",
    price: 6.49,
    image: "https://picsum.photos/300/300?random=44",
    category: ProductCategory.DESSERT,
  },
  {
    id: 1,
    name: "Espresso",
    price: 3.99,
    image: "https://picsum.photos/300/300?random=1",
    category: ProductCategory.COFFEE,
  },
  {
    id: 29,
    name: "French Toast",
    price: 7.99,
    image: "https://picsum.photos/300/300?random=39",
    category: ProductCategory.FOOD,
  },
  {
    id: 44,
    name: "Macarons (6 pack)",
    price: 8.99,
    image: "https://picsum.photos/300/300?random=52",
    category: ProductCategory.DESSERT,
  },
  {
    id: 15,
    name: "Gibraltar",
    price: 4.49,
    image: "https://picsum.photos/300/300?random=27",
    category: ProductCategory.COFFEE,
  },
  {
    id: 20,
    name: "Caesar Salad",
    price: 8.99,
    image: "https://picsum.photos/300/300?random=30",
    category: ProductCategory.FOOD,
  },
  {
    id: 31,
    name: "Blueberry Muffin",
    price: 3.29,
    image: "https://picsum.photos/300/300?random=7",
    category: ProductCategory.DESSERT,
  },
  {
    id: 8,
    name: "Matcha Latte",
    price: 4.89,
    image: "https://picsum.photos/300/300?random=11",
    category: ProductCategory.COFFEE,
  },
  {
    id: 27,
    name: "Breakfast Burrito",
    price: 8.99,
    image: "https://picsum.photos/300/300?random=37",
    category: ProductCategory.FOOD,
  },
  {
    id: 43,
    name: "Creme Brulee",
    price: 6.99,
    image: "https://picsum.photos/300/300?random=51",
    category: ProductCategory.DESSERT,
  },
  {
    id: 3,
    name: "Latte",
    price: 4.29,
    image: "https://picsum.photos/300/300?random=3",
    category: ProductCategory.COFFEE,
  },
  {
    id: 16,
    name: "Croissant",
    price: 2.99,
    image: "https://picsum.photos/300/300?random=6",
    category: ProductCategory.FOOD,
  },
  {
    id: 39,
    name: "Lemon Tart",
    price: 5.79,
    image: "https://picsum.photos/300/300?random=47",
    category: ProductCategory.DESSERT,
  },
  {
    id: 11,
    name: "Cold Brew",
    price: 3.89,
    image: "https://picsum.photos/300/300?random=23",
    category: ProductCategory.COFFEE,
  },
  {
    id: 24,
    name: "Club Sandwich",
    price: 9.49,
    image: "https://picsum.photos/300/300?random=34",
    category: ProductCategory.FOOD,
  },
  {
    id: 35,
    name: "Apple Pie",
    price: 4.99,
    image: "https://picsum.photos/300/300?random=43",
    category: ProductCategory.DESSERT,
  },
  {
    id: 14,
    name: "Vienna Coffee",
    price: 5.19,
    image: "https://picsum.photos/300/300?random=26",
    category: ProductCategory.COFFEE,
  },
  {
    id: 22,
    name: "Quinoa Bowl",
    price: 9.99,
    image: "https://picsum.photos/300/300?random=32",
    category: ProductCategory.FOOD,
  },
  {
    id: 46,
    name: "Chocolate Mousse",
    price: 5.49,
    image: "https://picsum.photos/300/300?random=54",
    category: ProductCategory.DESSERT,
  },
  {
    id: 6,
    name: "Iced Coffee",
    price: 4.19,
    image: "https://picsum.photos/300/300?random=8",
    category: ProductCategory.COFFEE,
  },
  {
    id: 30,
    name: "Eggs Benedict",
    price: 11.99,
    image: "https://picsum.photos/300/300?random=40",
    category: ProductCategory.FOOD,
  },
  {
    id: 40,
    name: "Chocolate Eclair",
    price: 4.79,
    image: "https://picsum.photos/300/300?random=48",
    category: ProductCategory.DESSERT,
  },
  {
    id: 2,
    name: "Cappuccino",
    price: 4.49,
    image: "https://picsum.photos/300/300?random=2",
    category: ProductCategory.COFFEE,
  },
  {
    id: 17,
    name: "Bagel with Cream Cheese",
    price: 3.99,
    image: "https://picsum.photos/300/300?random=10",
    category: ProductCategory.FOOD,
  },
  {
    id: 48,
    name: "Fruit Tart",
    price: 6.29,
    image: "https://picsum.photos/300/300?random=56",
    category: ProductCategory.DESSERT,
  },
  {
    id: 13,
    name: "Turkish Coffee",
    price: 4.99,
    image: "https://picsum.photos/300/300?random=25",
    category: ProductCategory.COFFEE,
  },
  {
    id: 28,
    name: "Acai Bowl",
    price: 10.99,
    image: "https://picsum.photos/300/300?random=38",
    category: ProductCategory.FOOD,
  },
  {
    id: 34,
    name: "Chocolate Brownie",
    price: 4.49,
    image: "https://picsum.photos/300/300?random=42",
    category: ProductCategory.DESSERT,
  },
  {
    id: 5,
    name: "Mocha",
    price: 4.79,
    image: "https://picsum.photos/300/300?random=5",
    category: ProductCategory.COFFEE,
  },
  {
    id: 26,
    name: "Panini",
    price: 7.99,
    image: "https://picsum.photos/300/300?random=36",
    category: ProductCategory.FOOD,
  },
  {
    id: 42,
    name: "Banana Bread",
    price: 3.99,
    image: "https://picsum.photos/300/300?random=50",
    category: ProductCategory.DESSERT,
  },
  {
    id: 10,
    name: "Macchiato",
    price: 4.69,
    image: "https://picsum.photos/300/300?random=22",
    category: ProductCategory.COFFEE,
  },
  {
    id: 19,
    name: "Grilled Sandwich",
    price: 7.49,
    image: "https://picsum.photos/300/300?random=29",
    category: ProductCategory.FOOD,
  },
  {
    id: 45,
    name: "Ice Cream Sundae",
    price: 4.99,
    image: "https://picsum.photos/300/300?random=53",
    category: ProductCategory.DESSERT,
  },
  {
    id: 9,
    name: "Flat White",
    price: 4.39,
    image: "https://picsum.photos/300/300?random=21",
    category: ProductCategory.COFFEE,
  },
  {
    id: 23,
    name: "Pasta Salad",
    price: 6.99,
    image: "https://picsum.photos/300/300?random=33",
    category: ProductCategory.FOOD,
  },
  {
    id: 33,
    name: "New York Cheesecake",
    price: 5.99,
    image: "https://picsum.photos/300/300?random=41",
    category: ProductCategory.DESSERT,
  },
  {
    id: 47,
    name: "Pecan Pie",
    price: 5.79,
    image: "https://picsum.photos/300/300?random=55",
    category: ProductCategory.DESSERT,
  },
  {
    id: 38,
    name: "Carrot Cake",
    price: 5.29,
    image: "https://picsum.photos/300/300?random=46",
    category: ProductCategory.DESSERT,
  },
  {
    id: 49,
    name: "Donut Assortment",
    price: 7.99,
    image: "https://picsum.photos/300/300?random=57",
    category: ProductCategory.DESSERT,
  },
  {
    id: 50,
    name: "Panna Cotta",
    price: 5.99,
    image: "https://picsum.photos/300/300?random=58",
    category: ProductCategory.DESSERT,
  },
];

export const INVENTORY: InventoryItem[] = [
  {
    id: 1,
    productName: "Chocolate Chip Cookie",
    sku: "DES-001",
    category: ProductCategory.DESSERT,
    quantity: 45,
    reorderLevel: 20,
    status: StockStatus.IN_STOCK,
    lastRestocked: "2024-10-01",
    image: "https://picsum.photos/300/300?random=12",
  },
  {
    id: 2,
    productName: "Americano",
    sku: "COF-001",
    category: ProductCategory.COFFEE,
    quantity: 15,
    reorderLevel: 20,
    status: StockStatus.LOW_STOCK,
    lastRestocked: "2024-09-28",
    image: "https://picsum.photos/300/300?random=13",
  },
  {
    id: 3,
    productName: "Chicken Wrap",
    sku: "FOO-001",
    category: ProductCategory.FOOD,
    quantity: 0,
    reorderLevel: 15,
    status: StockStatus.OUT_OF_STOCK,
    lastRestocked: "2024-09-25",
    image: "https://picsum.photos/300/300?random=14",
  },
  {
    id: 4,
    productName: "Strawberry Tart",
    sku: "DES-002",
    category: ProductCategory.DESSERT,
    quantity: 30,
    reorderLevel: 15,
    status: StockStatus.IN_STOCK,
    lastRestocked: "2024-10-02",
    image: "https://picsum.photos/300/300?random=15",
  },
  {
    id: 5,
    productName: "Chai Latte",
    sku: "COF-002",
    category: ProductCategory.COFFEE,
    quantity: 18,
    reorderLevel: 20,
    status: StockStatus.LOW_STOCK,
    lastRestocked: "2024-09-30",
    image: "https://picsum.photos/300/300?random=16",
  },
  {
    id: 6,
    productName: "Soup of the Day",
    sku: "FOO-002",
    category: ProductCategory.FOOD,
    quantity: 25,
    reorderLevel: 10,
    status: StockStatus.IN_STOCK,
    lastRestocked: "2024-10-03",
    image: "https://picsum.photos/300/300?random=17",
  },
  {
    id: 7,
    productName: "Red Velvet Cake",
    sku: "DES-003",
    category: ProductCategory.DESSERT,
    quantity: 8,
    reorderLevel: 10,
    status: StockStatus.LOW_STOCK,
    lastRestocked: "2024-09-29",
    image: "https://picsum.photos/300/300?random=18",
  },
  {
    id: 8,
    productName: "Frappuccino",
    sku: "COF-003",
    category: ProductCategory.COFFEE,
    quantity: 50,
    reorderLevel: 25,
    status: StockStatus.IN_STOCK,
    lastRestocked: "2024-10-01",
    image: "https://picsum.photos/300/300?random=19",
  },
  {
    id: 9,
    productName: "Avocado Toast",
    sku: "FOO-003",
    category: ProductCategory.FOOD,
    quantity: 22,
    reorderLevel: 15,
    status: StockStatus.IN_STOCK,
    lastRestocked: "2024-10-02",
    image: "https://picsum.photos/300/300?random=20",
  },
  {
    id: 10,
    productName: "Tiramisu",
    sku: "DES-004",
    category: ProductCategory.DESSERT,
    quantity: 12,
    reorderLevel: 10,
    status: StockStatus.IN_STOCK,
    lastRestocked: "2024-10-01",
    image: "https://picsum.photos/300/300?random=21",
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@coffeeshop.com",
    phone: "+1 (555) 123-4567",
    role: UserRole.ADMIN,
    status: UserStatus.ACTIVE,
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah.j@coffeeshop.com",
    phone: "+1 (555) 234-5678",
    role: UserRole.MANAGER,
    status: UserStatus.ACTIVE,
  },
  {
    id: "3",
    name: "Mike Davis",
    email: "mike.d@coffeeshop.com",
    phone: "+1 (555) 345-6789",
    role: UserRole.STAFF,
    status: UserStatus.ACTIVE,
  },
  {
    id: "4",
    name: "Emily Chen",
    email: "emily.chen@coffeeshop.com",
    phone: "+1 (555) 456-7890",
    role: UserRole.STAFF,
    status: UserStatus.INACTIVE,
  },
  {
    id: "5",
    name: "David Wilson",
    email: "d.wilson@coffeeshop.com",
    phone: "+1 (555) 567-8901",
    role: UserRole.MANAGER,
    status: UserStatus.ACTIVE,
  },
];
