import { Product } from "@/types/product.types";

export const PRODUCTS: Product[] = [
  // Coffee Items
  {
    id: 1,
    name: "Espresso",
    price: 3.99,
    image: "https://picsum.photos/300/300?random=1",
    category: "Coffee",
  },
  {
    id: 2,
    name: "Cappuccino",
    price: 4.49,
    image: "https://picsum.photos/300/300?random=2",
    category: "Coffee",
  },
  {
    id: 3,
    name: "Latte",
    price: 4.29,
    image: "https://picsum.photos/300/300?random=3",
    category: "Coffee",
  },
  {
    id: 4,
    name: "Americano",
    price: 3.49,
    image: "https://picsum.photos/300/300?random=4",
    category: "Coffee",
  },
  {
    id: 5,
    name: "Mocha",
    price: 4.79,
    image: "https://picsum.photos/300/300?random=5",
    category: "Coffee",
  },
  {
    id: 6,
    name: "Iced Coffee",
    price: 4.19,
    image: "https://picsum.photos/300/300?random=8",
    category: "Coffee",
  },
  {
    id: 7,
    name: "Chai Latte",
    price: 4.59,
    image: "https://picsum.photos/300/300?random=9",
    category: "Coffee",
  },
  {
    id: 8,
    name: "Matcha Latte",
    price: 4.89,
    image: "https://picsum.photos/300/300?random=11",
    category: "Coffee",
  },
  {
    id: 9,
    name: "Flat White",
    price: 4.39,
    image: "https://picsum.photos/300/300?random=21",
    category: "Coffee",
  },
  {
    id: 10,
    name: "Macchiato",
    price: 4.69,
    image: "https://picsum.photos/300/300?random=22",
    category: "Coffee",
  },
  {
    id: 11,
    name: "Cold Brew",
    price: 3.89,
    image: "https://picsum.photos/300/300?random=23",
    category: "Coffee",
  },
  {
    id: 12,
    name: "Frappuccino",
    price: 5.29,
    image: "https://picsum.photos/300/300?random=24",
    category: "Coffee",
  },
  {
    id: 13,
    name: "Turkish Coffee",
    price: 4.99,
    image: "https://picsum.photos/300/300?random=25",
    category: "Coffee",
  },
  {
    id: 14,
    name: "Vienna Coffee",
    price: 5.19,
    image: "https://picsum.photos/300/300?random=26",
    category: "Coffee",
  },
  {
    id: 15,
    name: "Gibraltar",
    price: 4.49,
    image: "https://picsum.photos/300/300?random=27",
    category: "Coffee",
  },

  // Food Items
  {
    id: 16,
    name: "Croissant",
    price: 2.99,
    image: "https://picsum.photos/300/300?random=6",
    category: "Food",
  },
  {
    id: 17,
    name: "Bagel with Cream Cheese",
    price: 3.99,
    image: "https://picsum.photos/300/300?random=10",
    category: "Food",
  },
  {
    id: 18,
    name: "Avocado Toast",
    price: 6.99,
    image: "https://picsum.photos/300/300?random=28",
    category: "Food",
  },
  {
    id: 19,
    name: "Grilled Sandwich",
    price: 7.49,
    image: "https://picsum.photos/300/300?random=29",
    category: "Food",
  },
  {
    id: 20,
    name: "Caesar Salad",
    price: 8.99,
    image: "https://picsum.photos/300/300?random=30",
    category: "Food",
  },
  {
    id: 21,
    name: "Chicken Wrap",
    price: 8.49,
    image: "https://picsum.photos/300/300?random=31",
    category: "Food",
  },
  {
    id: 22,
    name: "Quinoa Bowl",
    price: 9.99,
    image: "https://picsum.photos/300/300?random=32",
    category: "Food",
  },
  {
    id: 23,
    name: "Pasta Salad",
    price: 6.99,
    image: "https://picsum.photos/300/300?random=33",
    category: "Food",
  },
  {
    id: 24,
    name: "Club Sandwich",
    price: 9.49,
    image: "https://picsum.photos/300/300?random=34",
    category: "Food",
  },
  {
    id: 25,
    name: "Soup of the Day",
    price: 5.99,
    image: "https://picsum.photos/300/300?random=35",
    category: "Food",
  },
  {
    id: 26,
    name: "Panini",
    price: 7.99,
    image: "https://picsum.photos/300/300?random=36",
    category: "Food",
  },
  {
    id: 27,
    name: "Breakfast Burrito",
    price: 8.99,
    image: "https://picsum.photos/300/300?random=37",
    category: "Food",
  },
  {
    id: 28,
    name: "Acai Bowl",
    price: 10.99,
    image: "https://picsum.photos/300/300?random=38",
    category: "Food",
  },
  {
    id: 29,
    name: "French Toast",
    price: 7.99,
    image: "https://picsum.photos/300/300?random=39",
    category: "Food",
  },
  {
    id: 30,
    name: "Eggs Benedict",
    price: 11.99,
    image: "https://picsum.photos/300/300?random=40",
    category: "Food",
  },

  // Dessert Items
  {
    id: 31,
    name: "Blueberry Muffin",
    price: 3.29,
    image: "https://picsum.photos/300/300?random=7",
    category: "Dessert",
  },
  {
    id: 32,
    name: "Chocolate Chip Cookie",
    price: 2.49,
    image: "https://picsum.photos/300/300?random=12",
    category: "Dessert",
  },
  {
    id: 33,
    name: "New York Cheesecake",
    price: 5.99,
    image: "https://picsum.photos/300/300?random=41",
    category: "Dessert",
  },
  {
    id: 34,
    name: "Chocolate Brownie",
    price: 4.49,
    image: "https://picsum.photos/300/300?random=42",
    category: "Dessert",
  },
  {
    id: 35,
    name: "Apple Pie",
    price: 4.99,
    image: "https://picsum.photos/300/300?random=43",
    category: "Dessert",
  },
  {
    id: 36,
    name: "Tiramisu",
    price: 6.49,
    image: "https://picsum.photos/300/300?random=44",
    category: "Dessert",
  },
  {
    id: 37,
    name: "Strawberry Tart",
    price: 5.49,
    image: "https://picsum.photos/300/300?random=45",
    category: "Dessert",
  },
  {
    id: 38,
    name: "Carrot Cake",
    price: 5.29,
    image: "https://picsum.photos/300/300?random=46",
    category: "Dessert",
  },
  {
    id: 39,
    name: "Lemon Tart",
    price: 5.79,
    image: "https://picsum.photos/300/300?random=47",
    category: "Dessert",
  },
  {
    id: 40,
    name: "Chocolate Eclair",
    price: 4.79,
    image: "https://picsum.photos/300/300?random=48",
    category: "Dessert",
  },
  {
    id: 41,
    name: "Red Velvet Cake",
    price: 5.99,
    image: "https://picsum.photos/300/300?random=49",
    category: "Dessert",
  },
  {
    id: 42,
    name: "Banana Bread",
    price: 3.99,
    image: "https://picsum.photos/300/300?random=50",
    category: "Dessert",
  },
  {
    id: 43,
    name: "Creme Brulee",
    price: 6.99,
    image: "https://picsum.photos/300/300?random=51",
    category: "Dessert",
  },
  {
    id: 44,
    name: "Macarons (6 pack)",
    price: 8.99,
    image: "https://picsum.photos/300/300?random=52",
    category: "Dessert",
  },
  {
    id: 45,
    name: "Ice Cream Sundae",
    price: 4.99,
    image: "https://picsum.photos/300/300?random=53",
    category: "Dessert",
  },
  {
    id: 46,
    name: "Chocolate Mousse",
    price: 5.49,
    image: "https://picsum.photos/300/300?random=54",
    category: "Dessert",
  },
  {
    id: 47,
    name: "Pecan Pie",
    price: 5.79,
    image: "https://picsum.photos/300/300?random=55",
    category: "Dessert",
  },
  {
    id: 48,
    name: "Fruit Tart",
    price: 6.29,
    image: "https://picsum.photos/300/300?random=56",
    category: "Dessert",
  },
  {
    id: 49,
    name: "Donut Assortment",
    price: 7.99,
    image: "https://picsum.photos/300/300?random=57",
    category: "Dessert",
  },
  {
    id: 50,
    name: "Panna Cotta",
    price: 5.99,
    image: "https://picsum.photos/300/300?random=58",
    category: "Dessert",
  },
];
